global_exclude_dirs:
    - Symfony/app
    - Symfony/bin
    - Symfony/var
    - Symfony/vendor
    - Symfony/web

exclude_patterns:
    - Symfony/src/.htaccess

rules:
    web.default_favicon:
        enabled: false
    web.missing_favicon:
        enabled: false
